### ISSUE TITLE
[defect] 레이아웃 버그 제보

### ISSUE THREAD

**Issue by juunone** [Pewww/pr-tree-viewer#11]
![스크린샷 2021-05-11 18 29 14](https://user-images.githubusercontent.com/35126809/117793250-02aaa900-b287-11eb-85e9-4a7c52667d77.png)

- 버전
v1.1.3

- 문제정의
위 스크린샷 처럼 변경된 파일 만큼의 레이아웃 영역을 넘어서 박스가 보이는 현상이 나오고있습니다.

항상 잘 사용하고 있습니다 😄

**Comment by Pewww** [comment]
사용 감사드립니다 :D
빠른 시일 내로 해결하겠습니다!
확인이 늦은 점 죄송합니다🙏🏻

**Comment by Pewww** [comment]
@juunone 해당 이슈 해결되어 [1.1.4](https://chrome.google.com/webstore/detail/pr-tree-viewer/oohjmbbehcipaomlpikccfgncaknhenp/related?hl=ko) 버전 배포되었습니다.
버전이 자동으로 변경되지 않을 경우 재설치 부탁드리겠습니다.
감사합니다!
