### ISSUE TITLE
크롬 익스텐션 링크 오류?

### ISSUE THREAD

**Issue by woochanleee** [Pewww/pr-tree-viewer#16]
https://chrome.google.com/webstore/detail/pr-tree-viewer
로 접속하면 404 페이지로 연결되어서 찾아보니까 아래 링크로 접속시 잘 들어가지네요!
https://chrome.google.com/webstore/detail/pr-tree-viewer/oohjmbbehcipaomlpikccfgncaknhenp
레포 설명란과 리드미에 위 링크로 작성되어 있길래 이슈 남깁니다. 😊

**Comment by Pewww** [comment]
확인 감사합니다!
수정하였습니다~🙏
