### ISSUE TITLE
[improvement] 삭제된 파일의 경우 file tree 에서 취소선으로 표시 or 다른 표시

### ISSUE THREAD

**Issue by kizmo04** [Pewww/pr-tree-viewer#25]
삭제된 파일의 경우, file tree에서 취소선이나 다른 형태로 구분되어서 표시되면 좋을 것 같습니다~!

addition보다 deletion이 우세한 경우에도 아이콘이나 파일명의 색상이 다르게 구분되는 것도 좋을 것 같아용..!

**Comment by Pewww** [comment]
좋은 의견 주셔서 정말 감사합니다!
얘기주신 것 처럼 삭제된 파일의 경우 일반 변경 파일들과 명확히 구분될 수 있도록 취소선 표시 기능을 추가하여 현재 '배포 대기중' 상태에 있습니다.
다만, Addition과 Deletion에 따라 아이콘이나 파일명의 색상이 다르게 구분되는 내용은 현재로선 기획과 구현 내용이 명확하지 않아 일단 스킵하고자 합니다.
이 점 양해 부탁드리며 배포가 완료될 시 코멘트 남기도록 하겠습니다.
감사합니다 :D

**Comment by Pewww** [comment]
[1.1.8](https://chrome.google.com/webstore/detail/pr-tree-viewer/oohjmbbehcipaomlpikccfgncaknhenp) 버전 배포되었습니다!
확인 부탁드리겠습니다~!
