### ISSUE TITLE
tree-viewer 컨테이너 위에 패딩 추가 건의

### ISSUE THREAD

**Issue by hyp3rflow** [Pewww/pr-tree-viewer#3]
안녕하세요. pr-tree-viewer를 설치하여 잘 사용하고 있는 생활코딩 멤버입니다. :)
먼저, 좋은 프로젝트를 소개해주시고 관리해주셔서 감사하다는 말씀 전해드리고 싶습니다.

다름이 아니라, PR을 보는 중에 tree-viewer 쪽 컨테이너 위에 적당한 간격이 없어 너무 딱 붙어보이는 것 같은데, 혹시 괜찮으시다면 이 부분을 조금 띄워주시는 것도 가능할까요?

커멘트 남겨주시면 감사하겠습니다. :rocket:

![image](https://user-images.githubusercontent.com/49385012/110277678-1a607980-8019-11eb-8eae-08308deec998.png)

**Comment by Pewww** [comment]
안녕하세요!
익스텐션에 대해 관심을 가지고 사용해주셔서 정말 감사합니다 (_ _)

익스텐션이 스크롤 범위를 벗어날 때 ToolBar 쪽에 붙는 이슈는 인지하고 있는 상태입니다..!
다만, 현재 스타일 구조 상 스크립트로 해당 이슈를 해결해야 할 듯 하여 불필요한 연산이 들어가진 않을지 고민중인데,
좋은 방법을 찾아서 빠른 시일 내로 반영해보도록 하겠습니다 :D

다시 한 번 감사의 말씀 드립니다🙏

**Comment by hyp3rflow** [comment]
감사합니다 :)
괜찮으시다면 이슈를 닫아주셔도 좋을 것 같습니다.

**Comment by Pewww** [comment]
말씀주신 내용 반영하여 [1.1.2](https://chrome.google.com/webstore/detail/pr-tree-viewer/oohjmbbehcipaomlpikccfgncaknhenp?hl=ko&) 버전 배포하였습니다!
이슈는 닫도록 하겠습니다~ 감사합니다 :D
